In [9]:
import pandas as pd
import numpy as np

In [10]:
production = pd.read_csv("production_event.csv")
quality = pd.read_csv("quality_inspection.csv")
sensor = pd.read_csv("sensor_readings.csv")
supplier = pd.read_csv("supplier_master.csv")
bom = pd.read_csv("bom_master.csv")
workorder = pd.read_csv("work_orders.csv")
tool = pd.read_csv("tool_master.csv")
calibration = pd.read_csv("calibration_master.csv")
operator = pd.read_csv("operator_master.csv")
warranty = pd.read_csv("warranty_claims.csv")

In [11]:
production.head()

,Event_ID,VIN,Work_Order,Model,Line,Station,Timestamp,Part_Number,Supplier_Code,Operator_ID,Tool_ID,Shift
0,M7000,XX1 2 3 4,WO10000,Hatch Z,GA-1,STN-01,2026/03/01 06:70,eng-1001,NaN,EMP240,TL-032,B
1,M7001,MA1AB100000000001,WO10001,Sedan X,GA-1,stn-05,2026-03-01 6:01,ENG-1379,SUP-140,EMP144,TL-076,NaN
2,M7002,MA1AB100000000002,WO10002,Sedan X,GA-1,STN-01,2026-03-01 06:2,ENG-1111,SUP-060,EMP358,TL-078,A
3,M7003,MA1AB100000000003,WO10003,Hatch Z,GA-2,stn-05,2026-03-01 06:03,ENG-1332,SUP-180,EMP379,TL-054,B
4,M7004,MA1AB100000000004,WO10004,SUV Pro,PAINT-1,Stn-03,2026-03-01 06:05,ENG-1445,SUP-002,EMP181,TL-090,NaN

In [12]:
quality.head()

,Inspection_ID,Event_ID,VIN,Defect_Code,Defect,Inspection_Source,Inspector_ID,Rework_Flag,Scrap_Reason,Result
0,INSP10000,M7315,XX1 2 3 4,D003,ok,Human,INS69,N,NaN,FAIL
1,INSP10001,M11905,MA1AB100000004081,NONE,OK,Automated,INS83,N,Material,FAIL
2,INSP10002,M10227,MA1AB100000001443,D001,OK,Human,INS58,Y,NaN,PASS
3,INSP10003,M11197,MA1AB100000004063,D002,NaN,Automated,INS83,Y,Dimension,PASS
4,INSP10004,M7400,MA1AB100000004745,D001,Reject,Human,INS31,N,Weld,PASS

In [13]:
sensor.head()

,Reading_ID,Event_ID,Sensor_ID,Timestamp,Torque,Temperature,Pressure,Vibration_mm_s,Energy_kWh,Calibration_Factor
0,RD000001,M10346,SEN-034,2026/03/01 06:00:00,NaN,85C,4.5 bar,1.67,2.19,0.972
1,RD000002,M7955,SEN-037,2026-03-01 06:00:30,45 Nm,35 C,5.2 bar,6.63,5.67,0.988
2,RD000003,M10100,SEN-038,2026-03-01 06:01:00,60Nm,85C,65 psi,3.17,3.04,0.987
3,RD000004,M8302,SEN-008,2026-03-01 06:01:30,NaN,35 C,4.5 bar,2.44,2.87,1.027
4,RD000005,M9373,SEN-003,2026-03-01 06:02:00,35 lb-ft,104 F,4.5 bar,4.16,7.38,0.981

In [14]:
production.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Event_ID       5050 non-null   object
 1   VIN            5050 non-null   object
 2   Work_Order     5050 non-null   object
 3   Model          5050 non-null   object
 4   Line           5050 non-null   object
 5   Station        5050 non-null   object
 6   Timestamp      5050 non-null   object
 7   Part_Number    5050 non-null   object
 8   Supplier_Code  5026 non-null   object
 9   Operator_ID    5050 non-null   object
 10  Tool_ID        5050 non-null   object
 11  Shift          3797 non-null   object
dtypes: object(12)
memory usage: 473.6+ KB

In [15]:
quality.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Inspection_ID      4000 non-null   object
 1   Event_ID           4000 non-null   object
 2   VIN                4000 non-null   object
 3   Defect_Code        4000 non-null   object
 4   Defect             3338 non-null   object
 5   Inspection_Source  4000 non-null   object
 6   Inspector_ID       4000 non-null   object
 7   Rework_Flag        4000 non-null   object
 8   Scrap_Reason       3216 non-null   object
 9   Result             4000 non-null   object
dtypes: object(10)
memory usage: 312.6+ KB

In [16]:
sensor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Reading_ID          10000 non-null  object
 1   Event_ID            10000 non-null  object
 2   Sensor_ID           10000 non-null  object
 3   Timestamp           10000 non-null  object
 4   Torque              8386 non-null   object
 5   Temperature         8373 non-null   object
 6   Pressure            10000 non-null  object
 7   Vibration_mm_s      10000 non-null  float64
 8   Energy_kWh          10000 non-null  float64
 9   Calibration_Factor  10000 non-null  float64
dtypes: float64(3), object(7)
memory usage: 781.4+ KB

In [17]:
production.shape

(5050, 12)

In [18]:
production.columns

Index(['Event_ID', 'VIN', 'Work_Order', 'Model', 'Line', 'Station',
       'Timestamp', 'Part_Number', 'Supplier_Code', 'Operator_ID', 'Tool_ID',
       'Shift'],
      dtype='object')

In [19]:
production.dtypes

Event_ID         object
VIN              object
Work_Order       object
Model            object
Line             object
Station          object
Timestamp        object
Part_Number      object
Supplier_Code    object
Operator_ID      object
Tool_ID          object
Shift            object
dtype: object

In [20]:
production.isnull().sum()

Event_ID            0
VIN                 0
Work_Order          0
Model               0
Line                0
Station             0
Timestamp           0
Part_Number         0
Supplier_Code      24
Operator_ID         0
Tool_ID             0
Shift            1253
dtype: int64

In [21]:
production.duplicated().sum()

np.int64(47)

In [22]:
production.duplicated().sum()

np.int64(47)

In [23]:
production = production.drop_duplicates()

In [24]:
production["Station"].head(10)

0      STN-01
1     stn-05
2      STN-01
3     stn-05
4      Stn-03
5      STN-02
6      STN-03
7      STN-04
8     stn-05
9      Stn-03
Name: Station, dtype: object

In [25]:
production["Line"] = (
    production["Line"]
    .astype(str)
    .str.strip()
    .str.upper()
)

In [26]:
production["Station"] = (
    production["Station"]
    .astype(str)
    .str.strip()
    .str.upper()
)

In [27]:
print("\nAfter Cleaning:")
print(production[["Line", "Station"]].head(10))

After Cleaning:
      Line Station
0     GA-1  STN-01
1     GA-1  STN-05
2     GA-1  STN-01
3     GA-2  STN-05
4  PAINT-1  STN-03
5  PAINT-1  STN-02
6     GA-1  STN-03
7     GA-1  STN-04
8     GA-2  STN-05
9     GA-2  STN-03

In [28]:
production.to_csv("updated_production_events_cleaned_T1.csv", index=False)

print("\nLine and Station code cleaning completed successfully!")

Line and Station code cleaning completed successfully!

# TEST CASE 2

In [29]:
production = pd.read_csv("updated_production_events_cleaned_T1.csv")
print("Before Cleaning:")
print(production["Timestamp"].head(5))

Before Cleaning:
0    2026/03/01 06:70
1     2026-03-01 6:01
2     2026-03-01 06:2
3    2026-03-01 06:03
4    2026-03-01 06:05
Name: Timestamp, dtype: object

In [30]:
import re

def fix_timestamp(ts):
    ts = str(ts).strip().replace("/", "-")

    match = re.search(r'(\d{2}):(\d{2})', ts)

    if match:
        hour = int(match.group(1))
        minute = int(match.group(2))

        hour += minute // 60
        minute = minute % 60

        hour = hour % 24

        ts = re.sub(
            r'\d{2}:\d{2}',
            f"{hour:02d}:{minute:02d}",
            ts
        )

    return ts
production["Timestamp"] = production["Timestamp"].apply(fix_timestamp)

In [31]:
print("\nAfter Cleaning:")
print(production["Timestamp"].head(10))

After Cleaning:
0    2026-03-01 07:10
1     2026-03-01 6:01
2     2026-03-01 06:2
3    2026-03-01 06:03
4    2026-03-01 06:05
5    2026-03-01 06:06
6     2026-03-01 06:7
7    2026-03-01 06:08
8    2026-03-01 06:10
9    2026-03-01 06:11
Name: Timestamp, dtype: object

In [32]:
production.to_csv("production_events_cleaned_T2.csv", index=False)

print("\nTimestamp normalization completed successfully!")

Timestamp normalization completed successfully!

# Test Case 3

In [33]:
production = pd.read_csv("production_events_cleaned_T2.csv")
bom = pd.read_csv("bom_master.csv")

In [34]:
print("Before Cleaning:")
print(production["Part_Number"].head(10))

Before Cleaning:
0     eng-1001
1      ENG-1379
2      ENG-1111
3      ENG-1332
4      ENG-1445
5      ENG-1110
6      ENG-1433
7      ENG-1040
8      ENG-1035
9      ENG-1051
Name: Part_Number, dtype: object

In [35]:
production["Part_Number"] = (
    production["Part_Number"]
    .astype(str)
    .str.strip()
    .str.upper()                 
    .str.replace(" ", "", regex=False)   
)

In [36]:
production["Part_Number"] = production["Part_Number"].str.replace(
    r"([A-Z]+)(\d+)",
    r"\1-\2",
    regex=True
)

In [37]:
bom["Part_Number"] = (
    bom["Part_Number"]
    .astype(str)
    .str.strip()
    .str.upper()
    .str.replace(" ", "", regex=False)
)

In [38]:
bom["Part_Number"] = bom["Part_Number"].str.replace(
    r"([A-Z]+)(\d+)",
    r"\1-\2",
    regex=True
)

In [39]:
production = production.merge(
    bom[["Part_Number"]],
    on="Part_Number",
    how="left",
    indicator=True
)

In [40]:
production["BOM_Status"] = production["_merge"].map({
    "both": "Valid",
    "left_only": "Invalid"
})

In [41]:
production.drop(columns="_merge", inplace=True)

In [42]:
print("\nAfter Cleaning:")
print(production[["Part_Number", "BOM_Status"]].head(10))

After Cleaning:
  Part_Number BOM_Status
0    ENG-1001      Valid
1    ENG-1379      Valid
2    ENG-1111      Valid
3    ENG-1332      Valid
4    ENG-1445      Valid
5    ENG-1110      Valid
6    ENG-1433      Valid
7    ENG-1040      Valid
8    ENG-1035      Valid
9    ENG-1051      Valid

In [43]:
production.to_csv("production_events_cleaned_T3.csv", index=False)

print("\nPart Number normalization and BOM validation completed successfully!")

Part Number normalization and BOM validation completed successfully!

# Test Case 4

In [44]:
import re

In [45]:
sensor = pd.read_csv("sensor_readings.csv")

In [46]:
print("Before Cleaning:")
print(sensor["Torque"].head(10))

Before Cleaning:
0         NaN
1       45 Nm
2        60Nm
3         NaN
4    35 lb-ft
5       50 Nm
6    72 lb-ft
7       50 Nm
8       50 Nm
9    35 lb-ft
Name: Torque, dtype: object

In [47]:
def convert_to_nm(value):
    if pd.isna(value):
        return np.nan

    value = str(value).strip().lower()
    
    match = re.search(r'([\d.]+)\s*(nm|nmm|lb-ft)', value)

    if not match:
        return np.nan

    num = float(match.group(1))
    unit = match.group(2)

    if unit == "nm":
        return num
    elif unit == "nmm":
        return num / 1000
    elif unit == "lb-ft":
        return num * 1.35582

In [48]:
sensor["Torque_Nm"] = sensor["Torque"].apply(convert_to_nm)

sensor["Torque_Status"] = sensor["Torque_Nm"].apply(
    lambda x: "Valid" if pd.notna(x) else "Invalid"
)

In [49]:
print("\nAfter Cleaning:")
print(sensor[["Torque", "Torque_Nm", "Torque_Status"]].head(10))

sensor.to_csv("sensor_readings_cleaned_T4.csv", index=False)

print("\nTorque cleaning completed successfully!")

After Cleaning:
     Torque  Torque_Nm Torque_Status
0       NaN        NaN       Invalid
1     45 Nm   45.00000         Valid
2      60Nm   60.00000         Valid
3       NaN        NaN       Invalid
4  35 lb-ft   47.45370         Valid
5     50 Nm   50.00000         Valid
6  72 lb-ft   97.61904         Valid
7     50 Nm   50.00000         Valid
8     50 Nm   50.00000         Valid
9  35 lb-ft   47.45370         Valid

Torque cleaning completed successfully!

In [50]:
sensor["Torque"]

0            NaN
1          45 Nm
2           60Nm
3            NaN
4       35 lb-ft
          ...
9995         NaN
9996    35 lb-ft
9997    72 lb-ft
9998    35 lb-ft
9999    35 lb-ft
Name: Torque, Length: 10000, dtype: object

# Test case 5

In [51]:
sensor = pd.read_csv("sensor_readings_cleaned_T4.csv")

In [52]:
print("Before Cleaning:")
print(sensor["Temperature"].head(10))

Before Cleaning:
0      85C
1     35 C
2      85C
3     35 C
4    104 F
5     35 C
6      85C
7    104 F
8     35 C
9     95 F
Name: Temperature, dtype: object

In [53]:
def convert_to_celsius(temp):
    if pd.isna(temp):
        return np.nan

    temp = str(temp).strip().upper()

    num = re.findall(r"\d+\.?\d*", temp)

    if not num:
        return np.nan

    num = float(num[0])

    if "F" in temp:
        return round((num - 32) * 5 / 9, 2)

    elif "C" in temp:
        return num

    else:
        return num

In [54]:
sensor["Temperature_C"] = sensor["Temperature"].apply(convert_to_celsius)

sensor["Temperature_Status"] = sensor["Temperature_C"].apply(
    lambda x: "Valid" if pd.notna(x) else "Invalid"
)

In [55]:
print("\nAfter Cleaning:")
print(sensor[["Temperature", "Temperature_C", "Temperature_Status"]].head(10))

sensor.to_csv("sensor_readings_cleaned_T5.csv", index=False)

print("\nTemperature conversion completed successfully!")

After Cleaning:
  Temperature  Temperature_C Temperature_Status
0         85C           85.0              Valid
1        35 C           35.0              Valid
2         85C           85.0              Valid
3        35 C           35.0              Valid
4       104 F           40.0              Valid
5        35 C           35.0              Valid
6         85C           85.0              Valid
7       104 F           40.0              Valid
8        35 C           35.0              Valid
9        95 F           35.0              Valid

Temperature conversion completed successfully!

# Test Case 6

In [56]:

quality = pd.read_csv("quality_inspection.csv")
print("Before Cleaning:")
print(quality["Defect"].value_counts(dropna=False))

Before Cleaning:
Defect
Reject    690
reject    674
OK        672
NaN       662
Repair    654
 ok       648
Name: count, dtype: int64

In [57]:
quality["Defect"] = (
    quality["Defect"]
    .fillna("NONE")         
    .astype(str)
    .str.strip()             
    .str.upper()            
)

In [58]:
quality["Defect"] = quality["Defect"].replace({
    "NA": "NONE",
    "N/A": "NONE",
    "NULL": "NONE",
    "NAN": "NONE",
    "OKAY": "OK",
    "PASS": "OK",
    "GOOD": "OK",
    "REJECTED": "REJECT",
    "FAIL": "REJECT",
    "FAILED": "REJECT",
    "REWORK": "REPAIR",
    "FIX": "REPAIR"
})

In [59]:
valid_status = ["NONE", "OK", "REJECT", "REPAIR"]

quality["Defect"] = quality["Defect"].apply(
    lambda x: x if x in valid_status else "UNKNOWN"
)

In [60]:
print("\nAfter Cleaning:")
print(quality["Defect"].value_counts())

quality.to_csv("quality_inspection_cleaned_T6.csv", index=False)

print("\nDefect field normalization completed successfully!")

After Cleaning:
Defect
REJECT    1364
OK        1320
NONE       662
REPAIR     654
Name: count, dtype: int64

Defect field normalization completed successfully!

# Test Case 7

In [61]:
production = pd.read_csv("production_events_cleaned_T3.csv")
print("Before Cleaning:")
print(production["VIN"].head(10))

Before Cleaning:
0            XX1 2 3 4
1    MA1AB100000000001
2    MA1AB100000000002
3    MA1AB100000000003
4    MA1AB100000000004
5    MA1AB100000000005
6    MA1AB100000000006
7    MA1AB100000000007
8    MA1AB100000000008
9    MA1AB100000000009
Name: VIN, dtype: object

In [62]:
production["VIN"] = (
    production["VIN"]
    .astype(str)
    .str.strip()
    .str.upper()
    .str.replace(" ", "", regex=False)
)

In [63]:
production["VIN_Status"] = production["VIN"].apply(
    lambda x: "Valid" if len(x) == 17 else "Invalid"
)

def mask_vin(vin):
    if len(vin) == 17:
        return "*" * 13 + vin[-4:]
    else:
        return np.nan

In [64]:
production["Masked_VIN"] = production["VIN"].apply(mask_vin)

print("\nAfter Cleaning:")
print(production[["VIN", "VIN_Status", "Masked_VIN"]].head(10))

After Cleaning:
                 VIN VIN_Status         Masked_VIN
0             XX1234    Invalid                NaN
1  MA1AB100000000001      Valid  *************0001
2  MA1AB100000000002      Valid  *************0002
3  MA1AB100000000003      Valid  *************0003
4  MA1AB100000000004      Valid  *************0004
5  MA1AB100000000005      Valid  *************0005
6  MA1AB100000000006      Valid  *************0006
7  MA1AB100000000007      Valid  *************0007
8  MA1AB100000000008      Valid  *************0008
9  MA1AB100000000009      Valid  *************0009

In [65]:
production["Masked_VIN"] = production["VIN"].astype(str).apply(
    lambda x: x[:4] + "*" * (len(x)-7) + x[-3:]
)

In [66]:
export_data = production.copy()
export_data["VIN"] = export_data["Masked_VIN"]
export_data.drop(columns=["Masked_VIN"], inplace=True)

export_data.to_csv("production_events_cleaned_T7.csv", index=False)

print("\nVIN validation and masking completed successfully!")

VIN validation and masking completed successfully!

# Test Case 8

In [67]:
production = pd.read_csv("production_events_cleaned_T7.csv")
supplier = pd.read_csv("supplier_master.csv")

In [68]:
print("Before Cleaning:")
print(production["Supplier_Code"].head(10))

Before Cleaning:
0        NaN
1    SUP-140
2    SUP-060
3    SUP-180
4    SUP-002
5    SUP-196
6    SUP-089
7    SUP-142
8    SUP-012
9    SUP-098
Name: Supplier_Code, dtype: object

In [69]:
production["Supplier_Code"] = (
    production["Supplier_Code"]
    .astype(str)
    .str.strip()
    .str.upper()
    .str.replace(" ", "", regex=False)
)

In [70]:
production["Supplier_Code"] = production["Supplier_Code"].str.replace(
    r"([A-Z]+)(\d+)",
    r"\1-\2",
    regex=True
)

In [71]:
production = production.merge(
    supplier,
    on="Supplier_Code",
    how="left",
    indicator=True
)

In [72]:
production["Supplier_Status"] = production["_merge"].map({
    "both": "Valid",
    "left_only": "Invalid"
})

In [73]:
production.drop(columns="_merge", inplace=True)

print("\nAfter Cleaning:")
print(production[[
    "Supplier_Code",
    "Supplier_Status"
]].head(10))

production.to_csv("production_events_cleaned_T8_production+supplier.csv", index=False)

print("\nSupplier Code Normalization and Master Join completed successfully!")

After Cleaning:
  Supplier_Code Supplier_Status
0           NAN         Invalid
1       SUP-140           Valid
2       SUP-060           Valid
3       SUP-180           Valid
4       SUP-002           Valid
5       SUP-196           Valid
6       SUP-089           Valid
7       SUP-142           Valid
8       SUP-012           Valid
9       SUP-098           Valid

Supplier Code Normalization and Master Join completed successfully!

# Test Case 9

In [74]:

production = pd.read_csv("production_events_cleaned_T8_production+supplier.csv")

print("Duplicate Records Before Cleaning:")
print(production.duplicated(subset=["VIN", "Station", "Timestamp"]).sum())

Duplicate Records Before Cleaning:
0

In [75]:
production["VIN"] = production["VIN"].astype(str).str.strip().str.upper()
production["Station"] = production["Station"].astype(str).str.strip().str.upper()

production["Timestamp"] = pd.to_datetime(
    production["Timestamp"],
    errors="coerce"
)

In [76]:
production = production.drop_duplicates(
    subset=["VIN", "Station", "Timestamp"],
    keep="first"
)

In [77]:
print("\nDuplicate Records After Cleaning:")
print(production.duplicated(subset=["VIN", "Station", "Timestamp"]).sum())

Duplicate Records After Cleaning:
0

In [78]:
production.to_csv("production_events_cleaned_T9.csv", index=False)

print("\nDuplicate event removal completed successfully!")

Duplicate event removal completed successfully!

# Test Case 10

In [79]:

sensor = pd.read_csv("sensor_readings_cleaned_T5.csv")
calibration = pd.read_csv("calibration_master.csv")

print("Sensor Readings:")
print(sensor.head())

print("\nCalibration Data:")
print(calibration.head())

Sensor Readings:
  Reading_ID Event_ID Sensor_ID            Timestamp    Torque Temperature  \
0   RD000001   M10346   SEN-034  2026/03/01 06:00:00       NaN         85C
1   RD000002    M7955   SEN-037  2026-03-01 06:00:30     45 Nm        35 C
2   RD000003   M10100   SEN-038  2026-03-01 06:01:00      60Nm         85C
3   RD000004    M8302   SEN-008  2026-03-01 06:01:30       NaN        35 C
4   RD000005    M9373   SEN-003  2026-03-01 06:02:00  35 lb-ft       104 F

  Pressure  Vibration_mm_s  Energy_kWh  Calibration_Factor  Torque_Nm  \
0  4.5 bar            1.67        2.19               0.972        NaN
1  5.2 bar            6.63        5.67               0.988    45.0000
2   65 psi            3.17        3.04               0.987    60.0000
3  4.5 bar            2.44        2.87               1.027        NaN
4  4.5 bar            4.16        7.38               0.981    47.4537

  Torque_Status  Temperature_C Temperature_Status
0       Invalid           85.0              Valid
1         Valid           35.0              Valid
2         Valid           85.0              Valid
3       Invalid           35.0              Valid
4         Valid           40.0              Valid

Calibration Data:
  Sensor_ID  Calibration_Factor Calibration_Date Next_Calibration_Date  \
0   SEN-001               0.991       2026-01-18            2026-07-17
1   SEN-002               1.018       2026-05-11            2026-11-07
2   SEN-003               0.997       2026-02-09            2026-08-08
3   SEN-004               0.983       2026-05-10            2026-11-06
4   SEN-005               0.994       2026-04-06            2026-10-03

   Engineer   Status    Plant
0  R. Kumar    Valid  Plant-C
1  R. Kumar  Expired  Plant-B
2  R. Kumar  Expired  Plant-C
3    P. Roy    Valid  Plant-C
4  S. Patel  Expired  Plant-A

In [80]:
sensor = sensor.merge(
    calibration[["Sensor_ID", "Calibration_Factor"]],
    on="Sensor_ID",
    how="left"
)

In [81]:
print(sensor.columns)
print(calibration.columns)

Index(['Reading_ID', 'Event_ID', 'Sensor_ID', 'Timestamp', 'Torque',
       'Temperature', 'Pressure', 'Vibration_mm_s', 'Energy_kWh',
       'Calibration_Factor_x', 'Torque_Nm', 'Torque_Status', 'Temperature_C',
       'Temperature_Status', 'Calibration_Factor_y'],
      dtype='object')
Index(['Sensor_ID', 'Calibration_Factor', 'Calibration_Date',
       'Next_Calibration_Date', 'Engineer', 'Status', 'Plant'],
      dtype='object')

In [82]:
sensor["Torque"] = (
    sensor["Torque"]
    .astype(str)
    .str.replace("Nm", "", case=False, regex=False)
    .str.replace("NM", "", regex=False)
    .str.strip()
)

sensor["Torque"] = pd.to_numeric(sensor["Torque"], errors="coerce")

sensor["Calibration_Factor_y"] = pd.to_numeric(
    sensor["Calibration_Factor_y"],
    errors="coerce"
)

In [83]:
sensor["Calibration_Factor_y"] = sensor["Calibration_Factor_y"].fillna(1.0)

sensor["Calibrated_Torque"] = (
    sensor["Torque"] * sensor["Calibration_Factor_y"]
).round(2)

sensor["Drift"] = (
    sensor["Calibrated_Torque"] - sensor["Torque"]
).round(2)

sensor["Calibration_Status"] = sensor["Drift"].apply(
    lambda x: "Within Limit" if abs(x) <= 2 else "Out of Calibration"
)

In [84]:
sensor[["Torque", "Calibration_Factor_y"]].head(10)

   Torque  Calibration_Factor_y
0     NaN                 1.016
1    45.0                 1.028
2    60.0                 0.981
3     NaN                 0.995
4     NaN                 0.997
5    50.0                 1.003
6     NaN                 1.003
7    50.0                 1.006
8    50.0                 1.013
9     NaN                 1.026

In [85]:
sensor.to_csv("sensor_readings_cleaned_T10.csv", index=False)

print("\nSensor calibration and drift check completed successfully!")

Sensor calibration and drift check completed successfully!