In [102]:
import  pandas as pd
import numpy as np

In [103]:
production = pd.read_csv("production_raw.csv")

bom = pd.read_csv("bom_master.csv")

supplier = pd.read_csv("supplier_master.csv")

calibration = pd.read_csv("calibration_master.csv")

tool = pd.read_csv("tool_master.csv")

In [104]:
production.head()

,VIN,Work_Order,Station,Line,Timestamp,Part_Number,Supplier_Code,Torque,Temperature,Pressure,Defect,Inspection_Source,Tool_ID,Operator_ID,Shift,Scrap_Reason
0,INVALID VIN,WO100000,ST01,L03,2026-07-01 06:00:00,eng-1001,NaN,45 Nm,104 F,5.62,Reject,Human,TL999,EMP156,B,Material
1,MA1AB100000000001,WO100001,ST05,L03,2026-07-01 06:01:15,ENG-1386,SUP1160,45 Nm,42 C,5.49,OK,Automated,TL094,EMP123,C,Paint Defect
2,MA1AB100000000002,WO100002,st02,L01,2026-07-01 06:02:30,ENG-1102,SUP9999,50Nm,95 F,3.95,Repair,Automated,TL999,EMP305,A,Dimension
3,MA1AB100000000003,WO100003,ST02,L01,2026-07-01 06:03:45,ENG-1386,NaN,NaN,42 C,3.46,Repair,Human,TL034,EMP216,C,Paint Defect
4,MA1AB100000000004,WO100004,st02,L03,2026-07-01 06:05:00,eng-1001,NaN,35 lb-ft,104 F,3.27,reject,Automated,TL079,EMP265,A,Dimension

In [105]:
production.info()

<class 'pandas.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   VIN                5050 non-null   str
 1   Work_Order         5050 non-null   str
 2   Station            5050 non-null   str
 3   Line               5050 non-null   str
 4   Timestamp          5050 non-null   str
 5   Part_Number        5050 non-null   str
 6   Supplier_Code      3341 non-null   str
 7   Torque             3739 non-null   str
 8   Temperature        5050 non-null   str
 9   Pressure           5050 non-null   float64
 10  Defect             4215 non-null   str
 11  Inspection_Source  5050 non-null   str
 12  Tool_ID            5050 non-null   str
 13  Operator_ID        5050 non-null   str
 14  Shift              3750 non-null   str
 15  Scrap_Reason       4045 non-null   str
dtypes: float64(1), str(15)
memory usage: 631.4 KB

In [106]:
production.shape

(5050, 16)

In [107]:
print("Before Cleaning")
production[["Station", "Line"]].head(10)

Before Cleaning

  Station Line
0    ST01  L03
1    ST05  L03
2   st02   L01
3    ST02  L01
4   st02   L03
5    ST05  L03
6   st02   L03
7    ST04  L02
8    ST01  L01
9    ST03  L03

In [108]:
production["Station"] = (
    production["Station"]
    .astype(str)
    .str.strip()
    .str.upper()
)

In [109]:
production["Line"] = (
    production["Line"]
    .astype(str)
    .str.strip()
    .str.upper()
)

In [110]:
print("After Cleaning")
production[["Station", "Line"]].head(10)

After Cleaning

  Station Line
0    ST01  L03
1    ST05  L03
2    ST02  L01
3    ST02  L01
4    ST02  L03
5    ST05  L03
6    ST02  L03
7    ST04  L02
8    ST01  L01
9    ST03  L03

In [111]:
print("Unique Station Values:")
print(production["Station"].unique())

print("\nUnique Line Values:")
print(production["Line"].unique())

Unique Station Values:
<StringArray>
['ST01', 'ST05', 'ST02', 'ST04', 'ST03', 'ST06']
Length: 6, dtype: str

Unique Line Values:
<StringArray>
['L03', 'L01', 'L02']
Length: 3, dtype: str

In [112]:
production.to_csv("production_after_testcase1.csv", index=False)

print("Test Case 1 completed and saved successfully!")

Test Case 1 completed and saved successfully!

# Test Case 2: Timestamp Normalization & Invalid Minute Fix

### Objective
Standardize the Timestamp column by converting it into a proper datetime format. Invalid timestamps should be identified and handled safely.

### Expected Outcome
- All timestamps are stored in a consistent datetime format.
- Invalid timestamps are converted to NaT.

In [113]:
production.columns

Index(['VIN', 'Work_Order', 'Station', 'Line', 'Timestamp', 'Part_Number',
       'Supplier_Code', 'Torque', 'Temperature', 'Pressure', 'Defect',
       'Inspection_Source', 'Tool_ID', 'Operator_ID', 'Shift', 'Scrap_Reason'],
      dtype='str')

In [114]:
print("Before Normalization")
production["Timestamp"].head(10)

Before Normalization

0    2026-07-01 06:00:00
1    2026-07-01 06:01:15
2    2026-07-01 06:02:30
3    2026-07-01 06:03:45
4    2026-07-01 06:05:00
5    2026-07-01 06:06:15
6    2026-07-01 06:07:30
7    2026-07-01 06:08:45
8    2026-07-01 06:10:00
9    2026-07-01 06:11:15
Name: Timestamp, dtype: str

In [115]:
production["Timestamp"].dtype

In [116]:
production["Timestamp"] = pd.to_datetime(
    production["Timestamp"],
    errors="coerce"
)

In [117]:
print("After Normalization")
production["Timestamp"].head(10)

After Normalization

0   2026-07-01 06:00:00
1   2026-07-01 06:01:15
2   2026-07-01 06:02:30
3   2026-07-01 06:03:45
4   2026-07-01 06:05:00
5   2026-07-01 06:06:15
6   2026-07-01 06:07:30
7   2026-07-01 06:08:45
8   2026-07-01 06:10:00
9   2026-07-01 06:11:15
Name: Timestamp, dtype: datetime64[us]

In [118]:
production["Timestamp"].dtype

dtype('<M8[us]')

In [119]:
invalid_timestamps = production["Timestamp"].isna().sum()

print("Number of Invalid Timestamps:", invalid_timestamps)

Number of Invalid Timestamps: 0

In [120]:
production.to_csv("production_after_testcase2.csv", index=False)

print("Test Case 2 completed successfully!")

Test Case 2 completed successfully!

# Test Case 3: Part Number Normalization & BOM Validation

### Objective
Normalize all part numbers by removing extra spaces, converting them to uppercase, and validating each part number against the BOM (Bill of Materials) master dataset.

### Expected Outcome
- Part numbers are standardized.
- Invalid part numbers are identified.

In [121]:
print("Before Normalization")
production["Part_Number"].head(10)

Before Normalization

0     eng-1001
1      ENG-1386
2      ENG-1102
3      ENG-1386
4     eng-1001
5      ENG-1209
6      ENG-1380
7     eng-1001
8     eng-1001
9     eng-1001
Name: Part_Number, dtype: str

In [122]:
production["Part_Number"] = (
    production["Part_Number"]
    .astype(str)
    .str.strip()
    .str.upper()
)

In [123]:
print("After Normalization")
production["Part_Number"].head(10)

After Normalization

0    ENG-1001
1    ENG-1386
2    ENG-1102
3    ENG-1386
4    ENG-1001
5    ENG-1209
6    ENG-1380
7    ENG-1001
8    ENG-1001
9    ENG-1001
Name: Part_Number, dtype: str

In [124]:
production["Part_Number"].unique()

<StringArray>
['ENG-1001', 'ENG-1386', 'ENG-1102', 'ENG-1209', 'ENG-1380', 'ENG-1311',
 'ENG-1231', 'ENG-1092', 'ENG-1207', 'ENG-1173',
 ...
 'ENG-1497', 'ENG-1107', 'ENG-1272', 'ENG-1194', 'ENG-1115', 'ENG-1319',
 'ENG-1283', 'ENG-1356', 'ENG-1162', 'ENG-1121']
Length: 500, dtype: str

In [125]:
bom.head()

  Part_Number Part_Name BOM_Version Effective_From
0    ENG-1000      Seat          V1     2026-01-01
1    ENG-1001      Seat          V1     2026-01-01
2    ENG-1002   Battery          V2     2026-01-01
3    ENG-1003   Battery          V3     2026-01-01
4    ENG-1004      Seat          V1     2026-01-01

In [126]:
bom.columns

Index(['Part_Number', 'Part_Name', 'BOM_Version', 'Effective_From'], dtype='str')

In [127]:
bom["Part_Number"] = (
    bom["Part_Number"]
    .astype(str)
    .str.strip()
    .str.upper()
)

In [128]:
production["BOM_Status"] = production["Part_Number"].isin(bom["Part_Number"])

In [129]:
production["BOM_Status"] = production["BOM_Status"].map({
    True: "Valid",
    False: "Invalid"
})

In [130]:
production[["Part_Number", "BOM_Status"]].head(10)

  Part_Number BOM_Status
0    ENG-1001      Valid
1    ENG-1386      Valid
2    ENG-1102      Valid
3    ENG-1386      Valid
4    ENG-1001      Valid
5    ENG-1209      Valid
6    ENG-1380      Valid
7    ENG-1001      Valid
8    ENG-1001      Valid
9    ENG-1001      Valid

In [131]:
print(production["BOM_Status"].value_counts())

BOM_Status
Valid    5050
Name: count, dtype: int64

In [132]:
production.to_csv("production_after_testcase3.csv", index=False)

print("Test Case 3 completed successfully!")

Test Case 3 completed successfully!

# Test Case 4: Torque Numeric Parsing to Nm & Unit Checks

### Objective
Convert torque values into a numeric format (Nm) by removing unit text and validating the values.

### Expected Outcome
- Torque values are stored as numbers.
- Unit text such as "Nm" is removed.
- Invalid values become NaN.

In [133]:
print("Before Cleaning")
print(production["Torque"].head(10))

Before Cleaning
0       45 Nm
1       45 Nm
2        50Nm
3         NaN
4    35 lb-ft
5       45 Nm
6       45 Nm
7        50Nm
8    35 lb-ft
9        50Nm
Name: Torque, dtype: str

In [134]:
production["Torque"] = production["Torque"].astype(str)

production["Torque"] = production["Torque"].str.extract(r'(\d+\.?\d*)')[0]

production["Torque"] = pd.to_numeric(
    production["Torque"],
    errors="coerce"
)

In [135]:
print("After Cleaning")
print(production["Torque"].head(10))

After Cleaning
0    45.0
1    45.0
2    50.0
3     NaN
4    35.0
5    45.0
6    45.0
7    50.0
8    35.0
9    50.0
Name: Torque, dtype: float64

In [136]:
print("Torque Data Type:", production["Torque"].dtype)

print("\nMissing Torque Values:")
print(production["Torque"].isna().sum())

Torque Data Type: float64

Missing Torque Values:
1311

In [137]:
production.to_csv("production_after_testcase4.csv", index=False)

print("✅ Test Case 4 completed successfully!")

✅ Test Case 4 completed successfully!

# Test Case 5: Temperature Unit Parsing (C/F to Celsius)

## Objective
Standardize the Temperature column by converting all temperature values into Celsius (°C). If Fahrenheit values are present, convert them to Celsius. If values are already in Celsius, verify and retain them.

## Expected Outcome
- All temperatures are stored in Celsius.
- Invalid values are converted to NaN.
- Temperature data is standardized for further analysis.

In [138]:
print("Before Cleaning")
print(production["Temperature"].head(10))

print("\nData Type:")
print(production["Temperature"].dtype)

Before Cleaning
0    104 F
1     42 C
2     95 F
3     42 C
4    104 F
5     42 C
6    104 F
7     35 C
8     35 C
9     95 F
Name: Temperature, dtype: str

Data Type:
str

In [139]:
# Function to convert temperature to Celsius
def convert_to_celsius(temp):

    temp = str(temp).strip().upper()

    if temp.endswith("F"):
        value = float(temp.replace("F", "").strip())
        return round((value - 32) * 5 / 9, 2)

    elif temp.endswith("C"):
        value = float(temp.replace("C", "").strip())
        return value

    else:
        return None

# Apply conversion
production["Temperature"] = production["Temperature"].apply(convert_to_celsius)

In [140]:
print("After Cleaning")
print(production["Temperature"].head(10))

print("\nData Type:")
print(production["Temperature"].dtype)

After Cleaning
0    40.0
1    42.0
2    35.0
3    42.0
4    40.0
5    42.0
6    40.0
7    35.0
8    35.0
9    35.0
Name: Temperature, dtype: float64

Data Type:
float64

In [141]:
print("Missing Temperature Values:")
print(production["Temperature"].isna().sum())

print("\nTemperature Statistics:")
print(production["Temperature"].describe())

Missing Temperature Values:
0

Temperature Statistics:
count    5050.000000
mean       38.046337
std         3.081168
min        35.000000
25%        35.000000
50%        40.000000
75%        42.000000
max        42.000000
Name: Temperature, dtype: float64

In [142]:
production.to_csv("production_after_testcase5.csv", index=False)

print("✅ Test Case 5 completed successfully!")

✅ Test Case 5 completed successfully!

# Test Case 6: Defect Field Normalization

## Objective
Standardize the values in the `Defect` column by converting different representations into a consistent format.

## Expected Outcome
- All defect values follow a standard naming convention.
- Invalid or inconsistent entries are corrected.

In [143]:
print("Before Cleaning")
print(production["Defect"].head(15))

print("\nUnique Defect Values:")
print(production["Defect"].unique())

Before Cleaning
0     Reject
1         OK
2     Repair
3     Repair
4     reject
5         OK
6     Reject
7        NaN
8     reject
9         OK
10    Repair
11    Repair
12    reject
13        OK
14       ok
Name: Defect, dtype: str

Unique Defect Values:
<StringArray>
['Reject', 'OK', 'Repair', 'reject', nan, ' ok ']
Length: 6, dtype: str

In [144]:
print(production["Defect"].head(15))

print("\nUnique Defect Values:")
print(production["Defect"].unique())

0     Reject
1         OK
2     Repair
3     Repair
4     reject
5         OK
6     Reject
7        NaN
8     reject
9         OK
10    Repair
11    Repair
12    reject
13        OK
14       ok
Name: Defect, dtype: str

Unique Defect Values:
<StringArray>
['Reject', 'OK', 'Repair', 'reject', nan, ' ok ']
Length: 6, dtype: str

In [145]:
# Remove extra spaces
production["Defect"] = production["Defect"].str.strip()

# Convert to uppercase for uniform processing
production["Defect"] = production["Defect"].str.upper()

# Standardize defect values
production["Defect"] = production["Defect"].replace({
    "OK": "OK",
    "REJECT": "Reject",
    "REPAIR": "Repair"
})

In [146]:
print("After Cleaning")
print(production["Defect"].head(15))

print("\nUnique Defect Values:")
print(production["Defect"].unique())

After Cleaning
0     Reject
1         OK
2     Repair
3     Repair
4     Reject
5         OK
6     Reject
7        NaN
8     Reject
9         OK
10    Repair
11    Repair
12    Reject
13        OK
14        OK
Name: Defect, dtype: str

Unique Defect Values:
<StringArray>
['Reject', 'OK', 'Repair', nan]
Length: 4, dtype: str

In [147]:
print("Missing Defect Values:")
print(production["Defect"].isna().sum())

print("\nDefect Counts:")
print(production["Defect"].value_counts(dropna=False))

Missing Defect Values:
835

Defect Counts:
Defect
OK        1697
Reject    1684
NaN        835
Repair     834
Name: count, dtype: int64

In [148]:
production.to_csv("production_after_testcase6.csv", index=False)

print("✅ Test Case 6 completed successfully!")

✅ Test Case 6 completed successfully!

# Test Case 7: VIN Format Validation & Masking

## Objective
Validate that each Vehicle Identification Number (VIN) contains exactly 17 characters. Create a masked version of the VIN to protect sensitive information during data export.

## Expected Outcome
- VINs are validated.
- Invalid VINs are identified.
- A masked VIN column is created.

In [149]:
print("Before Validation")
print(production["VIN"].head(10))

print("\nVIN Lengths:")
print(production["VIN"].str.len().head(10))

Before Validation
0          INVALID VIN
1    MA1AB100000000001
2    MA1AB100000000002
3    MA1AB100000000003
4    MA1AB100000000004
5    MA1AB100000000005
6    MA1AB100000000006
7    MA1AB100000000007
8    MA1AB100000000008
9    MA1AB100000000009
Name: VIN, dtype: str

VIN Lengths:
0    11
1    17
2    17
3    17
4    17
5    17
6    17
7    17
8    17
9    17
Name: VIN, dtype: int64

In [150]:
# VIN Validation (Must be 17 characters)

production["VIN_Status"] = production["VIN"].apply(
    lambda x: "Valid" if len(str(x)) == 17 else "Invalid"
)

In [151]:
# Mask VIN for secure export
# Example:
# MA1AB100000000001
# becomes
# MA1***********001

production["Masked_VIN"] = production["VIN"].apply(
    lambda x: x[:5] + "*" * (len(x) - 8) + x[-3:]
    if len(str(x)) == 17
    else "INVALID VIN"
)

In [152]:
print("After Validation")

print(
    production[
        ["VIN", "VIN_Status", "Masked_VIN"]
    ].head(10)
)

After Validation
                 VIN VIN_Status         Masked_VIN
0        INVALID VIN    Invalid        INVALID VIN
1  MA1AB100000000001      Valid  MA1AB*********001
2  MA1AB100000000002      Valid  MA1AB*********002
3  MA1AB100000000003      Valid  MA1AB*********003
4  MA1AB100000000004      Valid  MA1AB*********004
5  MA1AB100000000005      Valid  MA1AB*********005
6  MA1AB100000000006      Valid  MA1AB*********006
7  MA1AB100000000007      Valid  MA1AB*********007
8  MA1AB100000000008      Valid  MA1AB*********008
9  MA1AB100000000009      Valid  MA1AB*********009

In [153]:
print("VIN Status Count:")
print(production["VIN_Status"].value_counts())

print("\nInvalid VIN Records:")
print(
    production[
        production["VIN_Status"] == "Invalid"
    ][["VIN"]]
)

VIN Status Count:
VIN_Status
Valid      5042
Invalid       8
Name: count, dtype: int64

Invalid VIN Records:
              VIN
0     INVALID VIN
777   INVALID VIN
1554  INVALID VIN
2331  INVALID VIN
3108  INVALID VIN
3885  INVALID VIN
4662   INVALIDVIN
5000   INVALIDVIN

In [154]:
production.to_csv("production_after_testcase7.csv", index=False)

print("✅ Test Case 7 completed successfully!")

✅ Test Case 7 completed successfully!

# Test Case 8: Supplier Code Normalization & Master Join

## Objective
Standardize supplier codes by removing extra spaces and converting them to uppercase. Validate each supplier code by matching it with the Supplier Master dataset.

## Expected Outcome
- Supplier codes are standardized.
- Valid supplier codes are identified.
- Invalid supplier codes are detected.

In [155]:
print("Production Supplier Codes:")
print(production["Supplier_Code"].head(15))

print("\nSupplier Master:")
print(supplier.head())

print("\nSupplier Master Columns:")
print(supplier.columns)

Production Supplier Codes:
0         NaN
1     SUP1160
2     SUP9999
3         NaN
4         NaN
5     SUP1035
6         NaN
7         NaN
8     SUP1062
9     SUP1037
10    SUP1013
11        NaN
12    SUP1016
13    SUP9999
14    SUP1017
Name: Supplier_Code, dtype: str

Supplier Master:
  Supplier_Code Supplier_Name  Country
0       SUP1000    Supplier_1    China
1       SUP1001    Supplier_2    India
2       SUP1002    Supplier_3    India
3       SUP1003    Supplier_4    China
4       SUP1004    Supplier_5  Germany

Supplier Master Columns:
Index(['Supplier_Code', 'Supplier_Name', 'Country'], dtype='str')

In [156]:
# Normalize Supplier Codes in Production Dataset
production["Supplier_Code"] = (
    production["Supplier_Code"]
    .astype(str)
    .str.strip()
    .str.upper()
)

# Normalize Supplier Codes in Supplier Master
supplier["Supplier_Code"] = (
    supplier["Supplier_Code"]
    .astype(str)
    .str.strip()
    .str.upper()
)

In [157]:
production["Supplier_Status"] = production["Supplier_Code"].isin(
    supplier["Supplier_Code"]
)

production["Supplier_Status"] = production["Supplier_Status"].map({
    True: "Valid",
    False: "Invalid"
})

In [158]:
production = production.merge(
    supplier,
    on="Supplier_Code",
    how="left"
)

In [159]:
print("After Cleaning")

print(
    production[
        [
            "Supplier_Code",
            "Supplier_Status",
            "Supplier_Name",
            "Country"
        ]
    ].head(15)
)

After Cleaning
   Supplier_Code Supplier_Status Supplier_Name   Country
0            NaN         Invalid           NaN       NaN
1        SUP1160           Valid  Supplier_161  Thailand
2        SUP9999         Invalid           NaN       NaN
3            NaN         Invalid           NaN       NaN
4            NaN         Invalid           NaN       NaN
5        SUP1035           Valid   Supplier_36  Thailand
6            NaN         Invalid           NaN       NaN
7            NaN         Invalid           NaN       NaN
8        SUP1062           Valid   Supplier_63     Korea
9        SUP1037           Valid   Supplier_38     India
10       SUP1013           Valid   Supplier_14     India
11           NaN         Invalid           NaN       NaN
12       SUP1016           Valid   Supplier_17     India
13       SUP9999         Invalid           NaN       NaN
14       SUP1017           Valid   Supplier_18     India

In [160]:
print("Supplier Status Summary:")
print(production["Supplier_Status"].value_counts())

print("\nInvalid Supplier Codes:")
print(
    production[
        production["Supplier_Status"] == "Invalid"
    ][["Supplier_Code"]].drop_duplicates()
)

Supplier Status Summary:
Supplier_Status
Invalid    3391
Valid      1659
Name: count, dtype: int64

Invalid Supplier Codes:
  Supplier_Code
0           NaN
2       SUP9999

In [161]:
production.to_csv("production_after_testcase8.csv", index=False)

print("✅ Test Case 8 completed successfully!")

✅ Test Case 8 completed successfully!

# Test Case 9: Duplicate Event Deduplication

## Objective
Identify duplicate production events using VIN, Station Code, and Timestamp.
Remove duplicate records while keeping the first occurrence.

## Expected Outcome
- Duplicate events are identified.
- Duplicate records are removed.
- Clean production data is generated.

In [162]:
print(production.columns)

Index(['VIN', 'Work_Order', 'Station', 'Line', 'Timestamp', 'Part_Number',
       'Supplier_Code', 'Torque', 'Temperature', 'Pressure', 'Defect',
       'Inspection_Source', 'Tool_ID', 'Operator_ID', 'Shift', 'Scrap_Reason',
       'BOM_Status', 'VIN_Status', 'Masked_VIN', 'Supplier_Status',
       'Supplier_Name', 'Country'],
      dtype='str')

In [163]:
print("Total duplicate rows:")
print(production.duplicated().sum())

Total duplicate rows:
49

In [164]:
print("Duplicate production events:")
print(
    production.duplicated(
        subset=["VIN", "Station", "Timestamp"]
    ).sum()
)

Duplicate production events:
49

In [165]:
duplicates = production[
    production.duplicated(
        subset=["VIN", "Station", "Timestamp"],
        keep=False
    )
]

print(duplicates[
    ["VIN", "Station", "Timestamp"]
].head(20))

                  VIN Station           Timestamp
1   MA1AB100000000001    ST05 2026-07-01 06:01:15
2   MA1AB100000000002    ST02 2026-07-01 06:02:30
3   MA1AB100000000003    ST02 2026-07-01 06:03:45
4   MA1AB100000000004    ST02 2026-07-01 06:05:00
5   MA1AB100000000005    ST05 2026-07-01 06:06:15
6   MA1AB100000000006    ST02 2026-07-01 06:07:30
7   MA1AB100000000007    ST04 2026-07-01 06:08:45
8   MA1AB100000000008    ST01 2026-07-01 06:10:00
9   MA1AB100000000009    ST03 2026-07-01 06:11:15
10  MA1AB100000000010    ST06 2026-07-01 06:12:30
11  MA1AB100000000011    ST04 2026-07-01 06:13:45
12  MA1AB100000000012    ST02 2026-07-01 06:15:00
13  MA1AB100000000013    ST04 2026-07-01 06:16:15
14  MA1AB100000000014    ST03 2026-07-01 06:17:30
15  MA1AB100000000015    ST02 2026-07-01 06:18:45
16  MA1AB100000000016    ST06 2026-07-01 06:20:00
17  MA1AB100000000017    ST06 2026-07-01 06:21:15
18  MA1AB100000000018    ST06 2026-07-01 06:22:30
19  MA1AB100000000019    ST03 2026-07-01 06:23:45
20  MA1AB100000000020    ST01 2026-07-01 06:25:00

In [166]:
production.duplicated(
    subset=["VIN", "Station", "Timestamp"]
).sum()

np.int64(49)

In [167]:
duplicates = production[
    production.duplicated(
        subset=["VIN", "Station", "Timestamp"],
        keep=False
    )
]

print("Duplicate Records Found:")
print(
    duplicates[
        ["VIN", "Station", "Timestamp"]
    ].head(20)
)

Duplicate Records Found:
                  VIN Station           Timestamp
1   MA1AB100000000001    ST05 2026-07-01 06:01:15
2   MA1AB100000000002    ST02 2026-07-01 06:02:30
3   MA1AB100000000003    ST02 2026-07-01 06:03:45
4   MA1AB100000000004    ST02 2026-07-01 06:05:00
5   MA1AB100000000005    ST05 2026-07-01 06:06:15
6   MA1AB100000000006    ST02 2026-07-01 06:07:30
7   MA1AB100000000007    ST04 2026-07-01 06:08:45
8   MA1AB100000000008    ST01 2026-07-01 06:10:00
9   MA1AB100000000009    ST03 2026-07-01 06:11:15
10  MA1AB100000000010    ST06 2026-07-01 06:12:30
11  MA1AB100000000011    ST04 2026-07-01 06:13:45
12  MA1AB100000000012    ST02 2026-07-01 06:15:00
13  MA1AB100000000013    ST04 2026-07-01 06:16:15
14  MA1AB100000000014    ST03 2026-07-01 06:17:30
15  MA1AB100000000015    ST02 2026-07-01 06:18:45
16  MA1AB100000000016    ST06 2026-07-01 06:20:00
17  MA1AB100000000017    ST06 2026-07-01 06:21:15
18  MA1AB100000000018    ST06 2026-07-01 06:22:30
19  MA1AB100000000019    ST03 2026-07-01 06:23:45
20  MA1AB100000000020    ST01 2026-07-01 06:25:00

In [168]:
production = production.drop_duplicates(
    subset=["VIN", "Station", "Timestamp"],
    keep="first"
)

print("Duplicates removed successfully!")

Duplicates removed successfully!

In [169]:
print("Remaining duplicate events:")

print(
    production.duplicated(
        subset=["VIN", "Station", "Timestamp"]
    ).sum()
)

Remaining duplicate events:
0

In [170]:
production.to_csv(
    "production_after_testcase9.csv",
    index=False
)

print("✅ Test Case 9 completed successfully!")

✅ Test Case 9 completed successfully!

In [171]:
production = production.drop_duplicates(
    subset=["VIN", "Station", "Timestamp"],
    keep="first"
)

print("Duplicates removed successfully!")

Duplicates removed successfully!

In [172]:
print("Remaining duplicate events:")

print(
    production.duplicated(
        subset=["VIN", "Station", "Timestamp"]
    ).sum()
)

Remaining duplicate events:
0

In [173]:
production.to_csv(
    "production_after_testcase9.csv",
    index=False
)

print("✅ Test Case 9 completed successfully!")

✅ Test Case 9 completed successfully!

# Test Case 10: Sensor Calibration & Drift Check

## Objective
Validate sensor readings by comparing production sensor data with the calibration master dataset.

The objective is to identify possible sensor drift or calibration issues by checking whether sensor measurements are within the expected calibration limits.

## Validation Parameters
- Tool ID matching with Calibration Master
- Torque value validation
- Temperature value validation
- Pressure value validation

## Expected Outcome
- Production sensor readings are compared against calibration limits.
- Sensors outside the acceptable range are flagged.
- Calibration status is assigned to each production record.
- Cleaned production data is generated for further analysis.

In [174]:
print("Calibration Master Columns:")
print(calibration.columns)

print("\nCalibration Master Sample:")
print(calibration.head())

Calibration Master Columns:
Index(['Sensor_ID', 'Calibration_Factor'], dtype='str')

Calibration Master Sample:
  Sensor_ID  Calibration_Factor
0    SEN001               1.007
1    SEN002               0.984
2    SEN003               1.011
3    SEN004               0.987
4    SEN005               0.984

In [175]:
print("Production Sensor Columns:")

print(
    production.columns
)

Production Sensor Columns:
Index(['VIN', 'Work_Order', 'Station', 'Line', 'Timestamp', 'Part_Number',
       'Supplier_Code', 'Torque', 'Temperature', 'Pressure', 'Defect',
       'Inspection_Source', 'Tool_ID', 'Operator_ID', 'Shift', 'Scrap_Reason',
       'BOM_Status', 'VIN_Status', 'Masked_VIN', 'Supplier_Status',
       'Supplier_Name', 'Country'],
      dtype='str')

In [176]:
print("Production Tool IDs:")
print(production["Tool_ID"].head(10))

print("\nCalibration Sensor IDs:")
print(calibration["Sensor_ID"].head(10))

Production Tool IDs:
0    TL999
1    TL094
2    TL999
3    TL034
4    TL079
5    TL031
6    TL999
7    TL059
8    TL076
9    TL999
Name: Tool_ID, dtype: str

Calibration Sensor IDs:
0    SEN001
1    SEN002
2    SEN003
3    SEN004
4    SEN005
5    SEN006
6    SEN007
7    SEN008
8    SEN009
9    SEN010
Name: Sensor_ID, dtype: str

In [177]:
# Extract numeric ID from Tool_ID and Sensor_ID

production["Sensor_Number"] = (
    production["Tool_ID"]
    .str.extract(r'(\d+)')
)

calibration["Sensor_Number"] = (
    calibration["Sensor_ID"]
    .str.extract(r'(\d+)')
)

print(production[["Tool_ID", "Sensor_Number"]].head())

print(calibration[["Sensor_ID", "Sensor_Number"]].head())

  Tool_ID Sensor_Number
0   TL999           999
1   TL094           094
2   TL999           999
3   TL034           034
4   TL079           079
  Sensor_ID Sensor_Number
0    SEN001           001
1    SEN002           002
2    SEN003           003
3    SEN004           004
4    SEN005           005

In [178]:
production = production.merge(
    calibration[
        ["Sensor_Number", "Calibration_Factor"]
    ],
    on="Sensor_Number",
    how="left"
)

print("Calibration data joined successfully!")

print(
    production[
        ["Tool_ID", "Sensor_Number", "Calibration_Factor"]
    ].head(15)
)

Calibration data joined successfully!
   Tool_ID Sensor_Number  Calibration_Factor
0    TL999           999                 NaN
1    TL094           094                 NaN
2    TL999           999                 NaN
3    TL034           034               0.987
4    TL079           079                 NaN
5    TL031           031               1.010
6    TL999           999                 NaN
7    TL059           059                 NaN
8    TL076           076                 NaN
9    TL999           999                 NaN
10   TL999           999                 NaN
11   TL088           088                 NaN
12   TL999           999                 NaN
13   TL999           999                 NaN
14   TL017           017               0.996

In [179]:
production["Calibration_Status"] = production["Calibration_Factor"].apply(
    lambda x: "Missing Calibration" 
    if pd.isna(x)
    else (
        "Normal"
        if 0.95 <= x <= 1.05
        else "Drift Detected"
    )
)

print(
    production[
        [
            "Tool_ID",
            "Calibration_Factor",
            "Calibration_Status"
        ]
    ].head(15)
)

   Tool_ID  Calibration_Factor   Calibration_Status
0    TL999                 NaN  Missing Calibration
1    TL094                 NaN  Missing Calibration
2    TL999                 NaN  Missing Calibration
3    TL034               0.987               Normal
4    TL079                 NaN  Missing Calibration
5    TL031               1.010               Normal
6    TL999                 NaN  Missing Calibration
7    TL059                 NaN  Missing Calibration
8    TL076                 NaN  Missing Calibration
9    TL999                 NaN  Missing Calibration
10   TL999                 NaN  Missing Calibration
11   TL088                 NaN  Missing Calibration
12   TL999                 NaN  Missing Calibration
13   TL999                 NaN  Missing Calibration
14   TL017               0.996               Normal

In [180]:
print("Calibration Status Summary:")
print(
    production["Calibration_Status"].value_counts()
)

Calibration Status Summary:
Calibration_Status
Missing Calibration    3711
Normal                 1290
Name: count, dtype: int64

In [181]:
print("Final Calibration Check:")

print(
    production[
        [
            "Tool_ID",
            "Calibration_Factor",
            "Calibration_Status"
        ]
    ].head(20)
)

print("\nCalibration Status Summary:")
print(
    production["Calibration_Status"].value_counts()
)

Final Calibration Check:
   Tool_ID  Calibration_Factor   Calibration_Status
0    TL999                 NaN  Missing Calibration
1    TL094                 NaN  Missing Calibration
2    TL999                 NaN  Missing Calibration
3    TL034               0.987               Normal
4    TL079                 NaN  Missing Calibration
5    TL031               1.010               Normal
6    TL999                 NaN  Missing Calibration
7    TL059                 NaN  Missing Calibration
8    TL076                 NaN  Missing Calibration
9    TL999                 NaN  Missing Calibration
10   TL999                 NaN  Missing Calibration
11   TL088                 NaN  Missing Calibration
12   TL999                 NaN  Missing Calibration
13   TL999                 NaN  Missing Calibration
14   TL017               0.996               Normal
15   TL999                 NaN  Missing Calibration
16   TL004               0.987               Normal
17   TL012               0.988               Normal
18   TL087                 NaN  Missing Calibration
19   TL999                 NaN  Missing Calibration

Calibration Status Summary:
Calibration_Status
Missing Calibration    3711
Normal                 1290
Name: count, dtype: int64

In [182]:
production.to_csv(
    "production_after_all_testcases.csv",
    index=False
)

print("✅ Test Case 10 completed successfully!")
print("🎉 All 10 Test Cases completed successfully!")

✅ Test Case 10 completed successfully!
🎉 All 10 Test Cases completed successfully!